# -*- coding: utf-8 -*-
"""EJERCICIO 2.5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oXocuALGW1lwR9-zzwfG2bOtSktufsJF
"""

class CuentaBancaria:
  def __init__(self, nombres_titular, apellidos_titular, numero_cuenta, tipo_cuenta):
    self.nombres_titular = nombres_titular
    self.apellidos_titular = apellidos_titular
    self.numero_cuenta = numero_cuenta
    self.tipo_cuenta = tipo_cuenta
    self.saldo = 0.0

  def imprimir(self):
    print(f"Nombres del titular = {self.nombres_titular}")
    print(f"Apellidos del titular = {self.apellidos_titular}")
    print(f"Número de cuenta = {self.numero_cuenta}")
    print(f"Tipo de cuenta = {self.tipo_cuenta}")
    print(f"Saldo = {self.saldo}")

  def consultar_saldo(self):
    print(f"El saldo de la cuenta es = {self.saldo}")

  def consignar(self, valor):
    if valor > 0:
      self.saldo += valor
      print(f"Se ha consignado ${valor} en la cuenta. El nuevo saldo es ${self.saldo}")
      return True
    else:
      print("El valor a consignar debe ser mayor a cero.")
      return False

  def retirar(self, valor):
    if valor > 0 and valor <= self.saldo:
      self.saldo -= valor
      print(f"Se ha retirado ${valor} en la cuenta. El nuevo saldo es ${self.saldo}")
      return True
    else:
      print("El valor a retirar debe ser menor que el saldo actual.")
      return False

cuenta = CuentaBancaria("Pedro", "Pérez", 123456789, "AHORROS")
cuenta.imprimir()
cuenta.consignar(200000)
cuenta.consignar(300000)
cuenta.retirar(400000)

_ = None
#ESTE SI