# -*- coding: utf-8 -*-
"""EJERCICIO 2.4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U8enLB26t_qbrgP4ucb1-6bEQDSaFlfg
"""

import math

class Circulo:
  def __init__(self, radio):
    self.radio = radio

  def calcular_area(self):
    return math.pi * (self.radio ** 2)

  def calcular_perimetro(self):
    return 2 * math.pi * self.radio

class Rectangulo:
  def __init__(self, base, altura):
    self.base = base
    self.altura = altura

  def calcular_area(self):
    return float(self.base * self.altura)

  def calcular_perimetro(self):
    return float((2 * self.base) + (2 * self.altura))


class Cuadrado:
  def __init__(self, lado):
    self.lado = lado

  def calcular_area(self):
    return float(self.lado * self.lado)

  def calcular_perimetro(self):
    return float(4 * self.lado)


class TrianguloRectangulo:
  def __init__(self, base, altura):
    self.base = base
    self.altura = altura

  def calcular_area(self):
    return float((self.base * self.altura) // 2)

  def calcular_hipotenusa(self):
    return math.sqrt((self.base ** 2) + (self.altura ** 2))

  def calcular_perimetro(self):
    return self.base + self.altura + self.calcular_hipotenusa()

  def determinar_tipo_triangulo(self):
    hipotenusa = self.calcular_hipotenusa()
    if self.base == self.altura and self.base == hipotenusa:
      print("Es un triángulo equilatero")
    elif self.base != self.altura and self.base != hipotenusa and self.altura != hipotenusa:
      print("Es un triángulo escaleno")
    else:
      print("Es un triángulo isósceles")

figura1 = Circulo(2)
figura2 = Rectangulo(1, 2)
figura3 = Cuadrado(3)
figura4 = TrianguloRectangulo(3, 5)

print(f"El área del círculo es = {figura1.calcular_area()}")
print(f"El perímetro del círculo es = {figura1.calcular_perimetro()}")
print()

print(f"El área del rectángulo es = {figura2.calcular_area()}")
print(f"El perímetro del rectángulo es = {figura2.calcular_perimetro()}")
print()

print(f"El área del cuadrado es = {figura3.calcular_area()}")
print(f"El perímetro del cuadrado es = {figura3.calcular_perimetro()}")
print()

print(f"El área del triángulo es = {figura4.calcular_area()}")
print(f"El perímetro del triángulo es = {figura4.calcular_perimetro()}")
figura4.determinar_tipo_triangulo()

#ESTE SI