# -*- coding: utf-8 -*-
"""EJERCICIO 2.3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12yxxZkt-mIPY2ZUq7HA4WYsf61HboZpF
"""

class Automovil:
  def __init__(self, marca, modelo, motor, tipo_combustible, tipo_automovil, numero_puertas, cantidad_asientos, velocidad_maxima, color):
    self.marca = marca
    self.modelo = modelo
    self.motor = motor
    self.tipo_combustible = tipo_combustible
    self.tipo_automovil = tipo_automovil
    self.numero_puertas = numero_puertas
    self.cantidad_asientos = cantidad_asientos
    self.velocidad_maxima = velocidad_maxima
    self.color = color
    self.velocidad_actual = 0

  def get_marca(self):return self.marca
  def set_marca(self, marca):self.marca = marca

  def get_modelo(self):return self.modelo
  def set_modelo(self, modelo):self.modelo = modelo

  def get_motor(self):return self.motor
  def set_motor(self, motor):self.motor = motor

  def get_tipo_combustible(self):return self.tipo_combustible
  def set_tipo_combustible(self, tipo_combustible):self.tipo_combustible = tipo_combustible

  def get_tipo_automovil(self):return self.tipo_automovil
  def set_tipo_automovil(self, tipo_automovil):self.tipo_automovil = tipo_automovil

  def get_numero_puertas(self):return self.numero_puertas
  def set_numero_puertas(self, numero_puertas):self.numero_puertas = numero_puertas

  def get_cantidad_asientos(self):return self.cantidad_asientos
  def set_cantidad_asientos(self, cantidad_asientos):self.cantidad_asientos = cantidad_asientos

  def get_velocidad_maxima(self):return self.velocidad_maxima
  def set_velocidad_maxima(self, velocidad_maxima):self.velocidad_maxima = velocidad_maxima

  def get_color(self):return self.color
  def set_color(self, color):self.color = color

  def get_velocidad_actual(self):return self.velocidad_actual
  def set_velocidad_actual(self, velocidad_actual):self.velocidad_actual = velocidad_actual

  def acelerar(self, incremento):
    if self.velocidad_actual + incremento <= self.velocidad_maxima:
      self.velocidad_actual += incremento
    else:
      print("No se puede incrementar a una velocidad superior a la máxima del automóvil.")

  def desacelerar(self, decremento):
    if self.velocidad_actual - decremento >= 0:
      self.velocidad_actual -= decremento
    else:
      print("No se puede decrementar a una velocidad negativa.")

  def frenar(self):
    self.velocidad_actual = 0

  def calcular_tiempo_llegada(self, distancia):
    if self.velocidad_actual > 0:
      return distancia / self.velocidad_actual
    return 0

  def imprimir(self):
    print(f"Marca = {self.marca}")
    print(f"Modelo = {self.modelo}")
    print(f"Motor = {self.motor}")
    print(f"Tipo de Combustible = {self.tipo_combustible}")
    print(f"Tipo de Automovil = {self.tipo_automovil}")
    print(f"Número de Puertas = {self.numero_puertas}")
    print(f"Cantidad de Asientos = {self.cantidad_asientos}")
    print(f"Velocidad Máxima = {self.velocidad_maxima}")
    print(f"Color = {self.color}")


auto1 = Automovil("Ford", 2018, 3, "DIESEL", "EJECUTIVO", 5, 6, 250, "NEGRO")
auto1.imprimir()
auto1.set_velocidad_actual(100)
print(f"Velocidad Actual = {auto1.velocidad_actual}")

auto1.acelerar(20)
print(f"Velocidad Actual = {auto1.velocidad_actual}")

auto1.desacelerar(50)
print(f"Velocidad Actual = {auto1.velocidad_actual}")

auto1.frenar()
print(f"Velocidad Actual = {auto1.velocidad_actual}")

auto1.desacelerar(20)

#ESTE Si