# -*- coding: utf-8 -*-
"""EJERCICIO 2.1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qsDbXiLdWFNr_86oXosIyj_nnr6Thg0S
"""

class Persona:

  def __init__(self, nombre, apellidos, numero_documento_identidad, ano_nacimiento):
    self.nombre = nombre
    self.apellidos = apellidos
    self.numero_documento_identidad = numero_documento_identidad
    self.ano_nacimiento = ano_nacimiento

  def imprimir(self):
    print(f"Nombre = {self.nombre}")
    print(f"Apellidos = {self.apellidos}")

    print(f"Número de documento de identidad = {self.numero_documento_identidad}")
    print(f"Año de nacimiento = {self.ano_nacimiento}")
    print()

p1 = Persona("Pedro", "Pérez", "1053121010", 1998)
p2 = Persona("Luis", "León", "1053223344", 2001)

p1.imprimir()
print()
p2.imprimir()

  #ESTE SI

