# -*- coding: utf-8 -*-
"""EJERCICIO 2.2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OXZV29pscd7mhiFjqIO8EMFjKglTh1FF
"""

class Planeta:
  def __init__(self, nombre, cantidad_satelites, masa, volumen, diametro, distancia_sol, tipo, es_observable):
    self.nombre = nombre
    self.cantidad_satelites = cantidad_satelites
    self.masa = masa
    self.volumen = volumen
    self.diametro = diametro
    self.distancia_sol = distancia_sol
    self.tipo = tipo
    self.es_observable = es_observable

  def imprimir(self):
    print(f"Nombre del Planeta = {self.nombre}")
    print(f"Cantidad de Satelites = {self.cantidad_satelites}")
    print(f"Masa del Planeta = {self.masa}")
    print(f"Volumen del Planeta = {self.volumen:E}")
    print(f"Diametro del Planeta = {self.diametro}")
    print(f"Distancia al sol = {self.distancia_sol}")
    print(f"Tipo de Planeta = {self.tipo}")
    print(f"Es observable = {self.es_observable}")

  def calcular_densidad(self):
      return self.masa / self.volumen
  def es_planeta_exterior(self):
      return self.distancia_sol > (149597870 * 3.4)

p1 = Planeta("Tierra", 1, 5.9736E24, 1.08321E12, 12742, 150000000, "TERRESTRE", True)
p1.imprimir()
print(f"Densidad del planeta = {p1.calcular_densidad():E}")
print(f"Es planeta exterior = {p1.es_planeta_exterior()}")
print()

p2 = Planeta("Júpiter", 79, 1.899E27, 1.4313E15, 139820, 750000000, "GASEOSO", True )
p2.imprimir()
print(f"Densidad del Planeta = {p2.calcular_densidad():E}")
print(f"Es planeta exterior = {p2.es_planeta_exterior()}")

#ESTE SI